# Generated by Django 6.0.1 on 2026-02-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_ziwauser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ziwauser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
